/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/bu6dqGlat7e
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link";
import { buttonVariants } from "@/components/ui/button";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuLabel,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";

export function Hero() {
  return (
    <section key="1" className="w-full pt-6 md:pt-12 lg:pt-16 xl:pt-24">
      <div className="container px-4 md:px-6">
        <div className="flex flex-col items-center space-y-4 text-center">
          <div className="space-y-2">
            <img className="mx-auto" src="kraft.png" width="60%"></img>
            {/* <p className="mx-auto max-w-[700px] text-gray-500 md:text-xl dark:text-gray-400">
              Em construção.
            </p> */}
          </div>
          <div className="flex flex-col gap-2 min-[400px]:flex-row">
            <DropdownMenu>
              <DropdownMenuTrigger
                className={buttonVariants({ variant: "default" })}
              >
                Contato
              </DropdownMenuTrigger>
              <DropdownMenuContent>
                <Link href="mailto:richardson@electrokraft.com.br">
                  <DropdownMenuItem>
                    <MailIcon className="mr-2 h-4 w-4" />
                    E-mail
                  </DropdownMenuItem>
                </Link>
                <Link href="#">
                  <DropdownMenuItem>
                    <PhoneIcon className="mr-2 h-4 w-4" />
                    WhatsApp
                  </DropdownMenuItem>
                </Link>
                <Link href="#">
                  <DropdownMenuItem>
                    <TelIcon className="mr-2 h-4 w-4" />
                    Telefone
                  </DropdownMenuItem>
                </Link>
              </DropdownMenuContent>
            </DropdownMenu>
            {/* <Link
              className={buttonVariants({ variant: "outline" })}
              href="https://instagram.com/electro_kraft"
            >
              Saiba mais
            </Link> */}
          </div>
        </div>
      </div>
    </section>
  );
}

function MailIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="20" height="16" x="2" y="4" rx="2" />
      <path d="m22 7-8.97 5.7a1.94 1.94 0 0 1-2.06 0L2 7" />
    </svg>
  );
}

function TelIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M22 16.92v3a2 2 0 0 1-2.18 2 19.79 19.79 0 0 1-8.63-3.07 19.5 19.5 0 0 1-6-6 19.79 19.79 0 0 1-3.07-8.67A2 2 0 0 1 4.11 2h3a2 2 0 0 1 2 1.72 12.84 12.84 0 0 0 .7 2.81 2 2 0 0 1-.45 2.11L8.09 9.91a16 16 0 0 0 6 6l1.27-1.27a2 2 0 0 1 2.11-.45 12.84 12.84 0 0 0 2.81.7A2 2 0 0 1 22 16.92z" />
    </svg>
  );
}

function PhoneIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="14" height="20" x="5" y="2" rx="2" ry="2" />
      <path d="M12 18h.01" />
    </svg>
  )
}
